a=int(input("Enter the first number:\n"))
b=int(input("Enter the second number:\n"))
c=int(input("Enter the third number:\n"))
d=int(input("Enter the fourth number:\n"))
e=int(input("Enter the fifth number:\n"))
f=int(input("Enter the sixth number:\n"))
g=int(input("Enter the seventh number:\n"))
h=int(input("Enter the Eighth number:\n"))
s={a,b,c,d,e,f,g,h}
print(s)